master_volume = 0.20000000298023224
scroll_speed = 450.0
hit_window_mode = "EtternaJudge"
hit_window_value = 4.0
aspect_ratio_mode = "Auto"
current_skin = "default"

[keybinds]
6 = [
    "KeyS",
    "KeyD",
    "KeyF",
    "KeyJ",
    "KeyK",
    "KeyL",
]
5 = [
    "KeyD",
    "KeyF",
    "Space",
    "KeyJ",
    "KeyK",
]
7 = [
    "KeyS",
    "KeyD",
    "KeyF",
    "Space",
    "KeyJ",
    "KeyK",
    "KeyL",
]
4 = [
    "KeyQ",
    "KeyW",
    "KeyO",
    "KeyP",
]
