master_volume = 0.6200000047683716
scroll_speed = 450.0
hit_window_mode = "OsuOD"
hit_window_value = 10.0
aspect_ratio_mode = "Auto"
current_skin = "default"

[keybinds]
7 = [
    "KeyS",
    "KeyD",
    "KeyF",
    "Space",
    "KeyJ",
    "KeyK",
    "KeyL",
]
6 = [
    "KeyS",
    "KeyD",
    "KeyF",
    "KeyJ",
    "KeyK",
    "KeyL",
]
4 = [
    "KeyZ",
    "KeyX",
    "KeyM",
    "Comma",
]
5 = [
    "KeyD",
    "KeyF",
    "Space",
    "KeyJ",
    "KeyK",
]
