master_volume = 0.6499999761581421
scroll_speed = 430.0
hit_window_mode = "EtternaJudge"
hit_window_value = 8.8
aspect_ratio_mode = "Auto"
current_skin = "default"

[keybinds]
4 = [
    "Â²",
    "&",
    "Home",
    "PageUp",
]
5 = [
    "KeyD",
    "KeyF",
    "Space",
    "KeyJ",
    "KeyK",
]
7 = [
    "KeyS",
    "KeyD",
    "KeyF",
    "Space",
    "KeyJ",
    "KeyK",
    "KeyL",
]
6 = [
    "KeyS",
    "KeyD",
    "KeyF",
    "KeyJ",
    "KeyK",
    "KeyL",
]
