receptor_color = [0.0, 0.0, 1.0, 1.0]
note_color = [1.0, 1.0, 1.0, 1.0]
selected_color = [1.0, 0.0, 0.0, 1.0]
difficulty_selected_color = [1.0, 1.0, 0.0, 1.0]

marv = [0.0, 1.0, 1.0, 1.0]
perfect = [1.0, 1.0, 0.0, 1.0]
great = [0.0, 1.0, 0.0, 1.0]
good = [0.0, 0.0, 0.5, 1.0]
bad = [1.0, 0.41, 0.71, 1.0]
miss = [1.0, 0.0, 0.0, 1.0]
ghost_tap = [0.5, 0.5, 0.5, 1.0]
