note_width_px = 166.0
note_height_px = 166.0
receptor_width_px = 188.0
receptor_height_px = 260.0
column_width_px = 192.0
receptor_spacing_px = 0.0
combo_text_size = 112.0
score_text_size = 50.0
accuracy_text_size = 32.0
judgement_text_size = 28.0
hit_bar_height_px = 42.0

[playfield_pos]
x = 942.0
y = -24.0

[combo_pos]
x = 970.0
y = 320.0

[score_pos]
x = 50.0
y = 58.0

[accuracy_pos]
x = 2.0
y = 244.0

[judgement_pos]
x = 354.0
y = 380.0

[judgement_flash_pos]
x = 984.0
y = 422.0

[hit_bar_pos]
x = 642.0
y = 454.0
