note_width_px = 166.0
note_height_px = 166.0
receptor_width_px = 198.0
receptor_height_px = 252.0
column_width_px = 192.0
receptor_spacing_px = 0.0
combo_text_size = 116.0
score_text_size = 50.0
accuracy_text_size = 32.0
judgement_text_size = 16.0
hit_bar_height_px = 34.0

[playfield_pos]
x = 960.0
y = -24.0

[combo_pos]
x = 978.0
y = 328.0

[score_pos]
x = 90.0
y = 76.0

[accuracy_pos]
x = 110.0
y = 244.0

[judgement_pos]
x = 350.0
y = 380.0

[judgement_flash_pos]
x = 984.0
y = 422.0

[hit_bar_pos]
x = 660.0
y = 460.0
